### ISSUE TITLE
Sending queries with parameters not in map hangs

### ISSUE THREAD

**Issue by epsilonhalbe** [zmactep/hasbolt#3] opened 2017-01-13 09:48 UTC
```
import           Database.Bolt           hiding (Value)
import qualified Data.Map.Strict         as M

main :: IO ()
main = do pipe <- connect $ def {user = "neo4j", password = neo4j}
          result <- run pipe $ queryP "MATCH (d {prop: {prop}}) return d;" M.empty
          putStr "Result:"
          print result
          close pipe
```

With a neo4j db in default config the above program does not terminate

**Comment by zmactep** [comment] 2017-01-13 10:04
Hi!

I cannot reproduce an issue on current master head:
```haskell
λ> pipe <- connect $ def {user = "neo4j", password = "neo4j"}
λ> result <- run pipe $ queryP "MATCH (n {prop: {prop}}) RETRUN n" M.empty
λ> print result
[]
```

**Comment by epsilonhalbe** [comment] 2017-01-13 16:01
there's a typo in your query - RETRUN /= RETURN

**Comment by zmactep** [comment] 2017-01-14 11:21
My fault. It shows one more problem: hasbolt does not provide error messages on syntax errors. I'll fix it, thank you!

**Comment by zmactep** [comment] 2017-01-14 12:35
@epsilonhalbe please check if latest commit works to you.

**Comment by epsilonhalbe** [comment] 2017-01-16 10:27
@zmactep no it does not work - my neo4j is a 3.1.0 - inside a docker container, I also tried the docker image for 3.0 which is (3.0.7 at the moment)

**Comment by epsilonhalbe** [comment] 2017-01-16 11:05
the docker command I use is

```
docker run --name neo4j --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/data:/data --volume=$HOME/neo4j/logs:/logs neo4j:3.1
```

and later `docker start neo4j`

**Comment by zmactep** [comment] 2017-01-16 11:51
It is deeply magical. I'll try on one more laptop, but as for now I have this:

with return:
<img width="1280" alt="2017-01-16 14 47 40" src="https://cloud.githubusercontent.com/assets/1034785/21981952/02bad31e-dbfb-11e6-8a0e-740fa8d76e89.png">

and without it:
<img width="1280" alt="2017-01-16 14 48 56" src="https://cloud.githubusercontent.com/assets/1034785/21981953/02bb4f38-dbfb-11e6-8f4b-61d3360616f7.png">

**Comment by epsilonhalbe** [comment] 2017-01-18 23:16
I have now tried this at home (new fresh docker container, linux native not in a vmware container) - and it works fine - so I will delete the docker container & image and all of the temporary files I have created and try it again tomorrow

**Comment by zmactep** [comment] 2017-01-19 06:53
Ok, thanks! I use OS X + Docker for Mac and CentOS 7 + native docker. Both work fine for me.

**Comment by zmactep** [comment] 2017-01-30 17:38
So, I close this issue, as I cannot reproduce it on any machine.

**Closed by zmactep** 2017-01-30 17:38 UTC
